[connections.snowflake]
account = "ACCOUNT-NAME"
user = "USERNAME"
role = "TRANSFORMER"
warehouse = "SAMPLE-WH"
database = "ANALYTICS"
schema = "MARTS"
private_key_file = "/Users/sampleuser/.ssh/snowflake_key_new.p8"
